### ISSUE TITLE
URDF imported objects lose mesh colliders when made into prefabs

### ISSUE THREAD

**Issue by gbattra** [Unity-Technologies/Unity-Robotics-Hub#187] opened 2021-03-23 00:22 UTC
**Unity Version:** 2020.3.0f1

If I make the imported robot arm into a prefab, it loses its mesh colliders.

Steps to reproduce:

1) Open up the `pick-n-place` tutorial project
2) Import the Niryo One arm using the URDF importer
3) Drag the new `niryo_one` instance into the `prefabs` directory
4) Open the newly made prefab and check the `mesh_collider` of any link (the mesh reference will be `None`)

Example:
![collider_bug](https://user-images.githubusercontent.com/5972117/112074203-2afe0d00-8b4c-11eb-97eb-8b37008f84df.png)

**Comment by vidurvij-Unity** [comment] 2021-03-23 17:16
Hi @gbattra,
Thanks for bringing this to our attention. I was able to reproduce this error. It seems that when the Robot is imported using VHACD decomposer, the meshes are saved in Assets because of which the prefab loose reference to the mesh files when reloaded. 
We will have fix for this issue as soon as possible.
Vidur

**Comment by vidurvij-Unity** [comment] 2021-04-13 23:09
@gbattra the issue has been fixed, Its in our dev branch and we update you as soon as it is merged in the main.

**Comment by vidurvij-Unity** [comment] 2021-05-10 19:56
@gbattra You should use version v0.3.0 of the URDF Importer. It has the fix in it. If the problem persists feel free to reopen the issue.

**Closed by vidurvij-Unity** 2021-05-10 19:56 UTC
